// <auto-generated />
using System;
using EmployeeRecords.DbEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeRecords.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20181016025334_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeRecords.DbEntities.Employee", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EmployeeDate");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("EmployeeNo")
                        .IsRequired();

                    b.Property<DateTime>("TerminatedDate");

                    b.HasKey("PersonId");

                    b.HasAlternateKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EmployeeRecords.DbEntities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("EmployeePersonId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("PersonId");

                    b.HasIndex("EmployeePersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("EmployeeRecords.DbEntities.Person", b =>
                {
                    b.HasOne("EmployeeRecords.DbEntities.Employee")
                        .WithMany("people")
                        .HasForeignKey("EmployeePersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
